/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_umit_icm_mobile_Main */

#ifndef _Included_org_umit_icm_mobile_Main
#define _Included_org_umit_icm_mobile_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_umit_icm_mobile_Main
 * Method:    getBoostTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_umit_icm_mobile_Main_getBoostTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
