// Generated by the protocol buffer compiler.  DO NOT EDIT!

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class WebsiteReportNormal extends
      com.google.protobuf.GeneratedMessage {
    // Use WebsiteReportNormal.newBuilder() to construct.
    private WebsiteReportNormal() {}
    
    private static final WebsiteReportNormal defaultInstance = new WebsiteReportNormal();
    public static WebsiteReportNormal getDefaultInstance() {
      return defaultInstance;
    }
    
    public WebsiteReportNormal getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProtos.internal_static_WebsiteReportNormal_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProtos.internal_static_WebsiteReportNormal_fieldAccessorTable;
    }
    
    // required int32 testID = 1;
    public static final int TESTID_FIELD_NUMBER = 1;
    private boolean hasTestID;
    private int testID_ = 0;
    public boolean hasTestID() { return hasTestID; }
    public int getTestID() { return testID_; }
    
    // required int64 timeUTC = 2;
    public static final int TIMEUTC_FIELD_NUMBER = 2;
    private boolean hasTimeUTC;
    private long timeUTC_ = 0L;
    public boolean hasTimeUTC() { return hasTimeUTC; }
    public long getTimeUTC() { return timeUTC_; }
    
    // required int32 statusCode = 3;
    public static final int STATUSCODE_FIELD_NUMBER = 3;
    private boolean hasStatusCode;
    private int statusCode_ = 0;
    public boolean hasStatusCode() { return hasStatusCode; }
    public int getStatusCode() { return statusCode_; }
    
    // required string responseContent = 4;
    public static final int RESPONSECONTENT_FIELD_NUMBER = 4;
    private boolean hasResponseContent;
    private java.lang.String responseContent_ = "";
    public boolean hasResponseContent() { return hasResponseContent; }
    public java.lang.String getResponseContent() { return responseContent_; }
    
    // required bool matchPattern = 5;
    public static final int MATCHPATTERN_FIELD_NUMBER = 5;
    private boolean hasMatchPattern;
    private boolean matchPattern_ = false;
    public boolean hasMatchPattern() { return hasMatchPattern; }
    public boolean getMatchPattern() { return matchPattern_; }
    
    // optional double bandwidth = 6;
    public static final int BANDWIDTH_FIELD_NUMBER = 6;
    private boolean hasBandwidth;
    private double bandwidth_ = 0D;
    public boolean hasBandwidth() { return hasBandwidth; }
    public double getBandwidth() { return bandwidth_; }
    
    public final boolean isInitialized() {
      if (!hasTestID) return false;
      if (!hasTimeUTC) return false;
      if (!hasStatusCode) return false;
      if (!hasResponseContent) return false;
      if (!hasMatchPattern) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasTestID()) {
        output.writeInt32(1, getTestID());
      }
      if (hasTimeUTC()) {
        output.writeInt64(2, getTimeUTC());
      }
      if (hasStatusCode()) {
        output.writeInt32(3, getStatusCode());
      }
      if (hasResponseContent()) {
        output.writeString(4, getResponseContent());
      }
      if (hasMatchPattern()) {
        output.writeBool(5, getMatchPattern());
      }
      if (hasBandwidth()) {
        output.writeDouble(6, getBandwidth());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTestID()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getTestID());
      }
      if (hasTimeUTC()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getTimeUTC());
      }
      if (hasStatusCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getStatusCode());
      }
      if (hasResponseContent()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getResponseContent());
      }
      if (hasMatchPattern()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, getMatchPattern());
      }
      if (hasBandwidth()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, getBandwidth());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static MessageProtos.WebsiteReportNormal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessageProtos.WebsiteReportNormal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.WebsiteReportNormal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessageProtos.WebsiteReportNormal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.WebsiteReportNormal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessageProtos.WebsiteReportNormal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.WebsiteReportNormal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static MessageProtos.WebsiteReportNormal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.WebsiteReportNormal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessageProtos.WebsiteReportNormal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MessageProtos.WebsiteReportNormal prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private MessageProtos.WebsiteReportNormal result;
      
      // Construct using MessageProtos.WebsiteReportNormal.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new MessageProtos.WebsiteReportNormal();
        return builder;
      }
      
      protected MessageProtos.WebsiteReportNormal internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new MessageProtos.WebsiteReportNormal();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProtos.WebsiteReportNormal.getDescriptor();
      }
      
      public MessageProtos.WebsiteReportNormal getDefaultInstanceForType() {
        return MessageProtos.WebsiteReportNormal.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public MessageProtos.WebsiteReportNormal build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private MessageProtos.WebsiteReportNormal buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public MessageProtos.WebsiteReportNormal buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        MessageProtos.WebsiteReportNormal returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageProtos.WebsiteReportNormal) {
          return mergeFrom((MessageProtos.WebsiteReportNormal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(MessageProtos.WebsiteReportNormal other) {
        if (other == MessageProtos.WebsiteReportNormal.getDefaultInstance()) return this;
        if (other.hasTestID()) {
          setTestID(other.getTestID());
        }
        if (other.hasTimeUTC()) {
          setTimeUTC(other.getTimeUTC());
        }
        if (other.hasStatusCode()) {
          setStatusCode(other.getStatusCode());
        }
        if (other.hasResponseContent()) {
          setResponseContent(other.getResponseContent());
        }
        if (other.hasMatchPattern()) {
          setMatchPattern(other.getMatchPattern());
        }
        if (other.hasBandwidth()) {
          setBandwidth(other.getBandwidth());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setTestID(input.readInt32());
              break;
            }
            case 16: {
              setTimeUTC(input.readInt64());
              break;
            }
            case 24: {
              setStatusCode(input.readInt32());
              break;
            }
            case 34: {
              setResponseContent(input.readString());
              break;
            }
            case 40: {
              setMatchPattern(input.readBool());
              break;
            }
            case 49: {
              setBandwidth(input.readDouble());
              break;
            }
          }
        }
      }
      
      
      // required int32 testID = 1;
      public boolean hasTestID() {
        return result.hasTestID();
      }
      public int getTestID() {
        return result.getTestID();
      }
      public Builder setTestID(int value) {
        result.hasTestID = true;
        result.testID_ = value;
        return this;
      }
      public Builder clearTestID() {
        result.hasTestID = false;
        result.testID_ = 0;
        return this;
      }
      
      // required int64 timeUTC = 2;
      public boolean hasTimeUTC() {
        return result.hasTimeUTC();
      }
      public long getTimeUTC() {
        return result.getTimeUTC();
      }
      public Builder setTimeUTC(long value) {
        result.hasTimeUTC = true;
        result.timeUTC_ = value;
        return this;
      }
      public Builder clearTimeUTC() {
        result.hasTimeUTC = false;
        result.timeUTC_ = 0L;
        return this;
      }
      
      // required int32 statusCode = 3;
      public boolean hasStatusCode() {
        return result.hasStatusCode();
      }
      public int getStatusCode() {
        return result.getStatusCode();
      }
      public Builder setStatusCode(int value) {
        result.hasStatusCode = true;
        result.statusCode_ = value;
        return this;
      }
      public Builder clearStatusCode() {
        result.hasStatusCode = false;
        result.statusCode_ = 0;
        return this;
      }
      
      // required string responseContent = 4;
      public boolean hasResponseContent() {
        return result.hasResponseContent();
      }
      public java.lang.String getResponseContent() {
        return result.getResponseContent();
      }
      public Builder setResponseContent(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasResponseContent = true;
        result.responseContent_ = value;
        return this;
      }
      public Builder clearResponseContent() {
        result.hasResponseContent = false;
        result.responseContent_ = getDefaultInstance().getResponseContent();
        return this;
      }
      
      // required bool matchPattern = 5;
      public boolean hasMatchPattern() {
        return result.hasMatchPattern();
      }
      public boolean getMatchPattern() {
        return result.getMatchPattern();
      }
      public Builder setMatchPattern(boolean value) {
        result.hasMatchPattern = true;
        result.matchPattern_ = value;
        return this;
      }
      public Builder clearMatchPattern() {
        result.hasMatchPattern = false;
        result.matchPattern_ = false;
        return this;
      }
      
      // optional double bandwidth = 6;
      public boolean hasBandwidth() {
        return result.hasBandwidth();
      }
      public double getBandwidth() {
        return result.getBandwidth();
      }
      public Builder setBandwidth(double value) {
        result.hasBandwidth = true;
        result.bandwidth_ = value;
        return this;
      }
      public Builder clearBandwidth() {
        result.hasBandwidth = false;
        result.bandwidth_ = 0D;
        return this;
      }
    }
    
    static {
      MessageProtos.getDescriptor();
    }
    
    static {
      MessageProtos.internalForceInit();
    }
  }
  
  public static final class WebsiteReportError extends
      com.google.protobuf.GeneratedMessage {
    // Use WebsiteReportError.newBuilder() to construct.
    private WebsiteReportError() {}
    
    private static final WebsiteReportError defaultInstance = new WebsiteReportError();
    public static WebsiteReportError getDefaultInstance() {
      return defaultInstance;
    }
    
    public WebsiteReportError getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProtos.internal_static_WebsiteReportError_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProtos.internal_static_WebsiteReportError_fieldAccessorTable;
    }
    
    // required int32 testID = 1;
    public static final int TESTID_FIELD_NUMBER = 1;
    private boolean hasTestID;
    private int testID_ = 0;
    public boolean hasTestID() { return hasTestID; }
    public int getTestID() { return testID_; }
    
    // required int64 timeUTC = 2;
    public static final int TIMEUTC_FIELD_NUMBER = 2;
    private boolean hasTimeUTC;
    private long timeUTC_ = 0L;
    public boolean hasTimeUTC() { return hasTimeUTC; }
    public long getTimeUTC() { return timeUTC_; }
    
    // required int32 statusCode = 3;
    public static final int STATUSCODE_FIELD_NUMBER = 3;
    private boolean hasStatusCode;
    private int statusCode_ = 0;
    public boolean hasStatusCode() { return hasStatusCode; }
    public int getStatusCode() { return statusCode_; }
    
    // required string redirectLink = 4;
    public static final int REDIRECTLINK_FIELD_NUMBER = 4;
    private boolean hasRedirectLink;
    private java.lang.String redirectLink_ = "";
    public boolean hasRedirectLink() { return hasRedirectLink; }
    public java.lang.String getRedirectLink() { return redirectLink_; }
    
    // required string listNodes = 5;
    public static final int LISTNODES_FIELD_NUMBER = 5;
    private boolean hasListNodes;
    private java.lang.String listNodes_ = "";
    public boolean hasListNodes() { return hasListNodes; }
    public java.lang.String getListNodes() { return listNodes_; }
    
    public final boolean isInitialized() {
      if (!hasTestID) return false;
      if (!hasTimeUTC) return false;
      if (!hasStatusCode) return false;
      if (!hasRedirectLink) return false;
      if (!hasListNodes) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasTestID()) {
        output.writeInt32(1, getTestID());
      }
      if (hasTimeUTC()) {
        output.writeInt64(2, getTimeUTC());
      }
      if (hasStatusCode()) {
        output.writeInt32(3, getStatusCode());
      }
      if (hasRedirectLink()) {
        output.writeString(4, getRedirectLink());
      }
      if (hasListNodes()) {
        output.writeString(5, getListNodes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTestID()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getTestID());
      }
      if (hasTimeUTC()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getTimeUTC());
      }
      if (hasStatusCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getStatusCode());
      }
      if (hasRedirectLink()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getRedirectLink());
      }
      if (hasListNodes()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getListNodes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static MessageProtos.WebsiteReportError parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessageProtos.WebsiteReportError parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.WebsiteReportError parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessageProtos.WebsiteReportError parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.WebsiteReportError parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessageProtos.WebsiteReportError parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.WebsiteReportError parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static MessageProtos.WebsiteReportError parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.WebsiteReportError parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessageProtos.WebsiteReportError parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MessageProtos.WebsiteReportError prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private MessageProtos.WebsiteReportError result;
      
      // Construct using MessageProtos.WebsiteReportError.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new MessageProtos.WebsiteReportError();
        return builder;
      }
      
      protected MessageProtos.WebsiteReportError internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new MessageProtos.WebsiteReportError();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProtos.WebsiteReportError.getDescriptor();
      }
      
      public MessageProtos.WebsiteReportError getDefaultInstanceForType() {
        return MessageProtos.WebsiteReportError.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public MessageProtos.WebsiteReportError build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private MessageProtos.WebsiteReportError buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public MessageProtos.WebsiteReportError buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        MessageProtos.WebsiteReportError returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageProtos.WebsiteReportError) {
          return mergeFrom((MessageProtos.WebsiteReportError)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(MessageProtos.WebsiteReportError other) {
        if (other == MessageProtos.WebsiteReportError.getDefaultInstance()) return this;
        if (other.hasTestID()) {
          setTestID(other.getTestID());
        }
        if (other.hasTimeUTC()) {
          setTimeUTC(other.getTimeUTC());
        }
        if (other.hasStatusCode()) {
          setStatusCode(other.getStatusCode());
        }
        if (other.hasRedirectLink()) {
          setRedirectLink(other.getRedirectLink());
        }
        if (other.hasListNodes()) {
          setListNodes(other.getListNodes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setTestID(input.readInt32());
              break;
            }
            case 16: {
              setTimeUTC(input.readInt64());
              break;
            }
            case 24: {
              setStatusCode(input.readInt32());
              break;
            }
            case 34: {
              setRedirectLink(input.readString());
              break;
            }
            case 42: {
              setListNodes(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required int32 testID = 1;
      public boolean hasTestID() {
        return result.hasTestID();
      }
      public int getTestID() {
        return result.getTestID();
      }
      public Builder setTestID(int value) {
        result.hasTestID = true;
        result.testID_ = value;
        return this;
      }
      public Builder clearTestID() {
        result.hasTestID = false;
        result.testID_ = 0;
        return this;
      }
      
      // required int64 timeUTC = 2;
      public boolean hasTimeUTC() {
        return result.hasTimeUTC();
      }
      public long getTimeUTC() {
        return result.getTimeUTC();
      }
      public Builder setTimeUTC(long value) {
        result.hasTimeUTC = true;
        result.timeUTC_ = value;
        return this;
      }
      public Builder clearTimeUTC() {
        result.hasTimeUTC = false;
        result.timeUTC_ = 0L;
        return this;
      }
      
      // required int32 statusCode = 3;
      public boolean hasStatusCode() {
        return result.hasStatusCode();
      }
      public int getStatusCode() {
        return result.getStatusCode();
      }
      public Builder setStatusCode(int value) {
        result.hasStatusCode = true;
        result.statusCode_ = value;
        return this;
      }
      public Builder clearStatusCode() {
        result.hasStatusCode = false;
        result.statusCode_ = 0;
        return this;
      }
      
      // required string redirectLink = 4;
      public boolean hasRedirectLink() {
        return result.hasRedirectLink();
      }
      public java.lang.String getRedirectLink() {
        return result.getRedirectLink();
      }
      public Builder setRedirectLink(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRedirectLink = true;
        result.redirectLink_ = value;
        return this;
      }
      public Builder clearRedirectLink() {
        result.hasRedirectLink = false;
        result.redirectLink_ = getDefaultInstance().getRedirectLink();
        return this;
      }
      
      // required string listNodes = 5;
      public boolean hasListNodes() {
        return result.hasListNodes();
      }
      public java.lang.String getListNodes() {
        return result.getListNodes();
      }
      public Builder setListNodes(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasListNodes = true;
        result.listNodes_ = value;
        return this;
      }
      public Builder clearListNodes() {
        result.hasListNodes = false;
        result.listNodes_ = getDefaultInstance().getListNodes();
        return this;
      }
    }
    
    static {
      MessageProtos.getDescriptor();
    }
    
    static {
      MessageProtos.internalForceInit();
    }
  }
  
  public static final class ServiceReportAllowed extends
      com.google.protobuf.GeneratedMessage {
    // Use ServiceReportAllowed.newBuilder() to construct.
    private ServiceReportAllowed() {}
    
    private static final ServiceReportAllowed defaultInstance = new ServiceReportAllowed();
    public static ServiceReportAllowed getDefaultInstance() {
      return defaultInstance;
    }
    
    public ServiceReportAllowed getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProtos.internal_static_ServiceReportAllowed_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProtos.internal_static_ServiceReportAllowed_fieldAccessorTable;
    }
    
    // required int32 testID = 1;
    public static final int TESTID_FIELD_NUMBER = 1;
    private boolean hasTestID;
    private int testID_ = 0;
    public boolean hasTestID() { return hasTestID; }
    public int getTestID() { return testID_; }
    
    // required int64 timeUTC = 2;
    public static final int TIMEUTC_FIELD_NUMBER = 2;
    private boolean hasTimeUTC;
    private long timeUTC_ = 0L;
    public boolean hasTimeUTC() { return hasTimeUTC; }
    public long getTimeUTC() { return timeUTC_; }
    
    // required bool statusCode = 3;
    public static final int STATUSCODE_FIELD_NUMBER = 3;
    private boolean hasStatusCode;
    private boolean statusCode_ = false;
    public boolean hasStatusCode() { return hasStatusCode; }
    public boolean getStatusCode() { return statusCode_; }
    
    // optional double bandwidth = 4;
    public static final int BANDWIDTH_FIELD_NUMBER = 4;
    private boolean hasBandwidth;
    private double bandwidth_ = 0D;
    public boolean hasBandwidth() { return hasBandwidth; }
    public double getBandwidth() { return bandwidth_; }
    
    public final boolean isInitialized() {
      if (!hasTestID) return false;
      if (!hasTimeUTC) return false;
      if (!hasStatusCode) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasTestID()) {
        output.writeInt32(1, getTestID());
      }
      if (hasTimeUTC()) {
        output.writeInt64(2, getTimeUTC());
      }
      if (hasStatusCode()) {
        output.writeBool(3, getStatusCode());
      }
      if (hasBandwidth()) {
        output.writeDouble(4, getBandwidth());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTestID()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getTestID());
      }
      if (hasTimeUTC()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getTimeUTC());
      }
      if (hasStatusCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, getStatusCode());
      }
      if (hasBandwidth()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, getBandwidth());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static MessageProtos.ServiceReportAllowed parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessageProtos.ServiceReportAllowed parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.ServiceReportAllowed parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessageProtos.ServiceReportAllowed parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.ServiceReportAllowed parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessageProtos.ServiceReportAllowed parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.ServiceReportAllowed parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static MessageProtos.ServiceReportAllowed parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.ServiceReportAllowed parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessageProtos.ServiceReportAllowed parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MessageProtos.ServiceReportAllowed prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private MessageProtos.ServiceReportAllowed result;
      
      // Construct using MessageProtos.ServiceReportAllowed.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new MessageProtos.ServiceReportAllowed();
        return builder;
      }
      
      protected MessageProtos.ServiceReportAllowed internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new MessageProtos.ServiceReportAllowed();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProtos.ServiceReportAllowed.getDescriptor();
      }
      
      public MessageProtos.ServiceReportAllowed getDefaultInstanceForType() {
        return MessageProtos.ServiceReportAllowed.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public MessageProtos.ServiceReportAllowed build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private MessageProtos.ServiceReportAllowed buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public MessageProtos.ServiceReportAllowed buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        MessageProtos.ServiceReportAllowed returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageProtos.ServiceReportAllowed) {
          return mergeFrom((MessageProtos.ServiceReportAllowed)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(MessageProtos.ServiceReportAllowed other) {
        if (other == MessageProtos.ServiceReportAllowed.getDefaultInstance()) return this;
        if (other.hasTestID()) {
          setTestID(other.getTestID());
        }
        if (other.hasTimeUTC()) {
          setTimeUTC(other.getTimeUTC());
        }
        if (other.hasStatusCode()) {
          setStatusCode(other.getStatusCode());
        }
        if (other.hasBandwidth()) {
          setBandwidth(other.getBandwidth());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setTestID(input.readInt32());
              break;
            }
            case 16: {
              setTimeUTC(input.readInt64());
              break;
            }
            case 24: {
              setStatusCode(input.readBool());
              break;
            }
            case 33: {
              setBandwidth(input.readDouble());
              break;
            }
          }
        }
      }
      
      
      // required int32 testID = 1;
      public boolean hasTestID() {
        return result.hasTestID();
      }
      public int getTestID() {
        return result.getTestID();
      }
      public Builder setTestID(int value) {
        result.hasTestID = true;
        result.testID_ = value;
        return this;
      }
      public Builder clearTestID() {
        result.hasTestID = false;
        result.testID_ = 0;
        return this;
      }
      
      // required int64 timeUTC = 2;
      public boolean hasTimeUTC() {
        return result.hasTimeUTC();
      }
      public long getTimeUTC() {
        return result.getTimeUTC();
      }
      public Builder setTimeUTC(long value) {
        result.hasTimeUTC = true;
        result.timeUTC_ = value;
        return this;
      }
      public Builder clearTimeUTC() {
        result.hasTimeUTC = false;
        result.timeUTC_ = 0L;
        return this;
      }
      
      // required bool statusCode = 3;
      public boolean hasStatusCode() {
        return result.hasStatusCode();
      }
      public boolean getStatusCode() {
        return result.getStatusCode();
      }
      public Builder setStatusCode(boolean value) {
        result.hasStatusCode = true;
        result.statusCode_ = value;
        return this;
      }
      public Builder clearStatusCode() {
        result.hasStatusCode = false;
        result.statusCode_ = false;
        return this;
      }
      
      // optional double bandwidth = 4;
      public boolean hasBandwidth() {
        return result.hasBandwidth();
      }
      public double getBandwidth() {
        return result.getBandwidth();
      }
      public Builder setBandwidth(double value) {
        result.hasBandwidth = true;
        result.bandwidth_ = value;
        return this;
      }
      public Builder clearBandwidth() {
        result.hasBandwidth = false;
        result.bandwidth_ = 0D;
        return this;
      }
    }
    
    static {
      MessageProtos.getDescriptor();
    }
    
    static {
      MessageProtos.internalForceInit();
    }
  }
  
  public static final class ServiceReportDenied extends
      com.google.protobuf.GeneratedMessage {
    // Use ServiceReportDenied.newBuilder() to construct.
    private ServiceReportDenied() {}
    
    private static final ServiceReportDenied defaultInstance = new ServiceReportDenied();
    public static ServiceReportDenied getDefaultInstance() {
      return defaultInstance;
    }
    
    public ServiceReportDenied getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProtos.internal_static_ServiceReportDenied_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProtos.internal_static_ServiceReportDenied_fieldAccessorTable;
    }
    
    // required int32 testID = 1;
    public static final int TESTID_FIELD_NUMBER = 1;
    private boolean hasTestID;
    private int testID_ = 0;
    public boolean hasTestID() { return hasTestID; }
    public int getTestID() { return testID_; }
    
    // required int64 timeUTC = 2;
    public static final int TIMEUTC_FIELD_NUMBER = 2;
    private boolean hasTimeUTC;
    private long timeUTC_ = 0L;
    public boolean hasTimeUTC() { return hasTimeUTC; }
    public long getTimeUTC() { return timeUTC_; }
    
    // required string listNodes = 3;
    public static final int LISTNODES_FIELD_NUMBER = 3;
    private boolean hasListNodes;
    private java.lang.String listNodes_ = "";
    public boolean hasListNodes() { return hasListNodes; }
    public java.lang.String getListNodes() { return listNodes_; }
    
    public final boolean isInitialized() {
      if (!hasTestID) return false;
      if (!hasTimeUTC) return false;
      if (!hasListNodes) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasTestID()) {
        output.writeInt32(1, getTestID());
      }
      if (hasTimeUTC()) {
        output.writeInt64(2, getTimeUTC());
      }
      if (hasListNodes()) {
        output.writeString(3, getListNodes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTestID()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getTestID());
      }
      if (hasTimeUTC()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getTimeUTC());
      }
      if (hasListNodes()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getListNodes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static MessageProtos.ServiceReportDenied parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessageProtos.ServiceReportDenied parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.ServiceReportDenied parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessageProtos.ServiceReportDenied parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.ServiceReportDenied parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessageProtos.ServiceReportDenied parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.ServiceReportDenied parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static MessageProtos.ServiceReportDenied parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static MessageProtos.ServiceReportDenied parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessageProtos.ServiceReportDenied parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MessageProtos.ServiceReportDenied prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private MessageProtos.ServiceReportDenied result;
      
      // Construct using MessageProtos.ServiceReportDenied.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new MessageProtos.ServiceReportDenied();
        return builder;
      }
      
      protected MessageProtos.ServiceReportDenied internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new MessageProtos.ServiceReportDenied();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProtos.ServiceReportDenied.getDescriptor();
      }
      
      public MessageProtos.ServiceReportDenied getDefaultInstanceForType() {
        return MessageProtos.ServiceReportDenied.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public MessageProtos.ServiceReportDenied build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private MessageProtos.ServiceReportDenied buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public MessageProtos.ServiceReportDenied buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        MessageProtos.ServiceReportDenied returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageProtos.ServiceReportDenied) {
          return mergeFrom((MessageProtos.ServiceReportDenied)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(MessageProtos.ServiceReportDenied other) {
        if (other == MessageProtos.ServiceReportDenied.getDefaultInstance()) return this;
        if (other.hasTestID()) {
          setTestID(other.getTestID());
        }
        if (other.hasTimeUTC()) {
          setTimeUTC(other.getTimeUTC());
        }
        if (other.hasListNodes()) {
          setListNodes(other.getListNodes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setTestID(input.readInt32());
              break;
            }
            case 16: {
              setTimeUTC(input.readInt64());
              break;
            }
            case 26: {
              setListNodes(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required int32 testID = 1;
      public boolean hasTestID() {
        return result.hasTestID();
      }
      public int getTestID() {
        return result.getTestID();
      }
      public Builder setTestID(int value) {
        result.hasTestID = true;
        result.testID_ = value;
        return this;
      }
      public Builder clearTestID() {
        result.hasTestID = false;
        result.testID_ = 0;
        return this;
      }
      
      // required int64 timeUTC = 2;
      public boolean hasTimeUTC() {
        return result.hasTimeUTC();
      }
      public long getTimeUTC() {
        return result.getTimeUTC();
      }
      public Builder setTimeUTC(long value) {
        result.hasTimeUTC = true;
        result.timeUTC_ = value;
        return this;
      }
      public Builder clearTimeUTC() {
        result.hasTimeUTC = false;
        result.timeUTC_ = 0L;
        return this;
      }
      
      // required string listNodes = 3;
      public boolean hasListNodes() {
        return result.hasListNodes();
      }
      public java.lang.String getListNodes() {
        return result.getListNodes();
      }
      public Builder setListNodes(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasListNodes = true;
        result.listNodes_ = value;
        return this;
      }
      public Builder clearListNodes() {
        result.hasListNodes = false;
        result.listNodes_ = getDefaultInstance().getListNodes();
        return this;
      }
    }
    
    static {
      MessageProtos.getDescriptor();
    }
    
    static {
      MessageProtos.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_WebsiteReportNormal_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_WebsiteReportNormal_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_WebsiteReportError_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_WebsiteReportError_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceReportAllowed_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServiceReportAllowed_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceReportDenied_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServiceReportDenied_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src/org/umit/icm/mobile/proto/Messages" +
      ".proto\"\214\001\n\023WebsiteReportNormal\022\016\n\006testID" +
      "\030\001 \002(\005\022\017\n\007timeUTC\030\002 \002(\003\022\022\n\nstatusCode\030\003 " +
      "\002(\005\022\027\n\017responseContent\030\004 \002(\t\022\024\n\014matchPat" +
      "tern\030\005 \002(\010\022\021\n\tbandwidth\030\006 \001(\001\"r\n\022Website" +
      "ReportError\022\016\n\006testID\030\001 \002(\005\022\017\n\007timeUTC\030\002" +
      " \002(\003\022\022\n\nstatusCode\030\003 \002(\005\022\024\n\014redirectLink" +
      "\030\004 \002(\t\022\021\n\tlistNodes\030\005 \002(\t\"^\n\024ServiceRepo" +
      "rtAllowed\022\016\n\006testID\030\001 \002(\005\022\017\n\007timeUTC\030\002 \002" +
      "(\003\022\022\n\nstatusCode\030\003 \002(\010\022\021\n\tbandwidth\030\004 \001(",
      "\001\"I\n\023ServiceReportDenied\022\016\n\006testID\030\001 \002(\005" +
      "\022\017\n\007timeUTC\030\002 \002(\003\022\021\n\tlistNodes\030\003 \002(\tB\017B\r" +
      "MessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_WebsiteReportNormal_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_WebsiteReportNormal_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_WebsiteReportNormal_descriptor,
              new java.lang.String[] { "TestID", "TimeUTC", "StatusCode", "ResponseContent", "MatchPattern", "Bandwidth", },
              MessageProtos.WebsiteReportNormal.class,
              MessageProtos.WebsiteReportNormal.Builder.class);
          internal_static_WebsiteReportError_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_WebsiteReportError_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_WebsiteReportError_descriptor,
              new java.lang.String[] { "TestID", "TimeUTC", "StatusCode", "RedirectLink", "ListNodes", },
              MessageProtos.WebsiteReportError.class,
              MessageProtos.WebsiteReportError.Builder.class);
          internal_static_ServiceReportAllowed_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ServiceReportAllowed_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ServiceReportAllowed_descriptor,
              new java.lang.String[] { "TestID", "TimeUTC", "StatusCode", "Bandwidth", },
              MessageProtos.ServiceReportAllowed.class,
              MessageProtos.ServiceReportAllowed.Builder.class);
          internal_static_ServiceReportDenied_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_ServiceReportDenied_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ServiceReportDenied_descriptor,
              new java.lang.String[] { "TestID", "TimeUTC", "ListNodes", },
              MessageProtos.ServiceReportDenied.class,
              MessageProtos.ServiceReportDenied.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
